/**
 * Prepares the generated inputs of the Angular docs (both gitignored):
 *
 *   - src/app/generated/page-sources.ts: the .html and .ts text of every docs page
 *     (src/app/pages/<name>/<name>-page.*), so each example's "show code" view displays the markup and
 *     code that actually render it, never a copy that can drift.
 *   - src/generated-assets/: the Blazor docs' shared assets (the category screenshots). Angular only
 *     serves assets from inside this app, so they are copied rather than committed twice.
 *
 *   node scripts/prepare.mts           # once (build)
 *   node scripts/prepare.mts --watch   # and again on every page change (serve)
 */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pagesDir = path.join(appRoot, "src/app/pages");
const outFile = path.join(appRoot, "src/app/generated/page-sources.ts");
const sharedAssets = path.resolve(appRoot, "../pb-design-system-docs/wwwroot/assets");
const assetsOut = path.join(appRoot, "src/generated-assets");

fs.rmSync(assetsOut, { recursive: true, force: true });
fs.cpSync(sharedAssets, assetsOut, { recursive: true });

function collect(): void {
  const sources: Record<string, { html: string; ts: string }> = {};
  for (const name of fs.readdirSync(pagesDir).sort()) {
    const read = (ext: string) => {
      const file = path.join(pagesDir, name, `${name}-page.${ext}`);
      return fs.existsSync(file) ? fs.readFileSync(file, "utf8").replaceAll("\r\n", "\n") : "";
    };
    const html = read("html");
    if (html) sources[name] = { html, ts: read("ts") };
  }
  const content =
    "// GENERATED by scripts/collect-sources.mts -- do not edit.\n\n" +
    "export const PAGE_SOURCES: Record<string, { html: string; ts: string }> = " +
    JSON.stringify(sources, null, 2) +
    ";\n";
  fs.mkdirSync(path.dirname(outFile), { recursive: true });
  // Only write on change, so the dev server doesn't rebuild for nothing.
  if (!fs.existsSync(outFile) || fs.readFileSync(outFile, "utf8") !== content) {
    fs.writeFileSync(outFile, content);
    console.log(`prepare: ${Object.keys(sources).length} pages -> ${path.relative(appRoot, outFile)}`);
  }
}

collect();

if (process.argv.includes("--watch")) {
  let timer: NodeJS.Timeout | undefined;
  fs.watch(pagesDir, { recursive: true }, () => {
    clearTimeout(timer);
    timer = setTimeout(collect, 100);
  });
  console.log("prepare: watching src/app/pages");
}
